//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManager.Models
{
    using Newtonsoft.Json;
    using System;

    using System.Collections.Generic;

    public partial class Request
    {
        public int RequestId { get; set; }
        public string UserName { get; set; }
        public System.DateTime RequestedOn { get; set; }
        public System.DateTime CheckoutTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string HostName { get; set; }
        public bool IsActive { get; set; }

        [JsonIgnore]
        public virtual Host Host { get; set; }

        public bool IsInProgress
        {
            get
            {
                return IsActive && !ReturnTime.HasValue;
            }
        }

    }
}
